In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Resources_Collection/BigQuant_Resources_Collection/00_General_Resources/General_Tool")
from cn_general_tool import *

from bigcharts import Kline

In [2]:
sd, ed, = get_sd_ed('2024-11-28', '2024-11-28')

### 1 Minute

In [3]:
sql_01m = """ 
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount,
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
)
SELECT * 
FROM data_base
"""

df_01m = get_dai_df(sql_01m, sd, ed, lag_min=240)
df_01m

,date,instrument,open,close,high,low,volume,amount
0,2024-11-28 09:25:00,600519.SH,1522.00,1522.00,1522.00,1522.00,31200,4.748640e+07
1,2024-11-28 09:31:00,600519.SH,1522.00,1511.06,1522.00,1510.01,90100,1.366267e+08
2,2024-11-28 09:32:00,600519.SH,1511.30,1513.95,1513.95,1511.05,56900,8.601926e+07
3,2024-11-28 09:33:00,600519.SH,1514.00,1517.55,1517.83,1513.85,38400,5.815474e+07
4,2024-11-28 09:34:00,600519.SH,1516.28,1516.85,1516.94,1513.94,19400,2.940162e+07
...,...,...,...,...,...,...,...,...
236,2024-11-28 14:56:00,600519.SH,1514.00,1513.00,1515.00,1512.51,17760,2.689244e+07
237,2024-11-28 14:57:00,600519.SH,1512.60,1514.94,1514.95,1512.00,11301,1.710923e+07
238,2024-11-28 14:58:00,600519.SH,1514.90,1514.90,1514.90,1514.90,100,1.514900e+05
239,2024-11-28 14:59:00,600519.SH,1514.90,1514.90,1514.90,1514.90,0,0.000000e+00
240,2024-11-28 15:00:00,600519.SH,1514.90,1518.00,1518.00,1514.90,99300,1.507374e+08

In [4]:
Kline(df_01m)

### 5 Minute

In [5]:
sql_05m = """
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount,
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
)
SELECT 
    date,
    instrument,
    DATE_TRUNC('hour', date) + INTERVAL '5 min' * CAST(FLOOR(EXTRACT(minute FROM date) / 5) AS BIGINT) AS _period,
    FIRST_VALUE(open) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS open,
    LAST_VALUE(close) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS close,
    MAX(high)         OVER (PARTITION BY _period, instrument) AS high,
    MIN(low)          OVER (PARTITION BY _period, instrument) AS low,
    SUM(amount)       OVER (PARTITION BY _period, instrument) AS amount,
    SUM(volume)       OVER (PARTITION BY _period, instrument) AS volume,
    row_number() OVER (PARTITION BY _period ORDER BY date) AS _rn,
FROM data_base
QUALIFY _rn = 1
ORDER BY date, instrument
"""

df_05m = get_dai_df(sql_05m, sd, ed, lag_min=240)
df_05m

,date,instrument,open,close,high,low,amount,volume
0,2024-11-28 09:25:00,600519.SH,1522.00,1522.00,1522.00,1522.00,4.748640e+07,31200
1,2024-11-28 09:31:00,600519.SH,1522.00,1516.85,1522.00,1510.01,3.102023e+08,204800
2,2024-11-28 09:35:00,600519.SH,1516.85,1519.10,1521.50,1515.00,1.439652e+08,94793
3,2024-11-28 09:40:00,600519.SH,1519.40,1524.16,1524.99,1519.40,1.715926e+08,112700
4,2024-11-28 09:45:00,600519.SH,1524.80,1522.16,1524.91,1521.02,1.043314e+08,68504
5,2024-11-28 09:50:00,600519.SH,1522.16,1520.50,1522.60,1520.50,8.034414e+07,52800
6,2024-11-28 09:55:00,600519.SH,1521.16,1519.29,1522.54,1519.20,8.866461e+07,58300
7,2024-11-28 10:00:00,600519.SH,1519.29,1518.30,1519.81,1517.00,7.348013e+07,48400
8,2024-11-28 10:05:00,600519.SH,1519.00,1517.35,1519.30,1516.98,6.102164e+07,40200
9,2024-11-28 10:10:00,600519.SH,1517.96,1515.01,1517.96,1515.00,7.387700e+07,48718
10,2024-11-28 10:15:00,600519.SH,1515.00,1514.13,1515.52,1513.00,8.313830e+07,54897
11,2024-11-28 10:20:00,600519.SH,1513.97,1514.77,1514.80,1513.00,5.253242e+07,34700
12,2024-11-28 10:25:00,600519.SH,1514.80,1514.12,1515.45,1513.96,5.573091e+07,36800
13,2024-11-28 10:30:00,600519.SH,1514.14,1514.09,1514.14,1512.95,6.083638e+07,40200
14,2024-11-28 10:35:00,600519.SH,1514.00,1513.80,1514.00,1513.00,5.297691e+07,35000
15,2024-11-28 10:40:00,600519.SH,1513.74,1512.20,1513.74,1512.06,6.186702e+07,40900
16,2024-11-28 10:45:00,600519.SH,1512.18,1513.27,1514.03,1512.10,5.613462e+07,37100
17,2024-11-28 10:50:00,600519.SH,1513.30,1512.83,1513.83,1512.32,4.947416e+07,32700
18,2024-11-28 10:55:00,600519.SH,1513.31,1513.35,1514.00,1512.84,5.221852e+07,34500
19,2024-11-28 11:00:00,600519.SH,1513.15,1510.70,1513.59,1510.66,9.499509e+07,62829
20,2024-11-28 11:05:00,600519.SH,1510.65,1508.78,1510.92,1508.00,1.080974e+08,71600
21,2024-11-28 11:10:00,600519.SH,1508.97,1508.10,1509.29,1508.06,6.426564e+07,42600
22,2024-11-28 11:15:00,600519.SH,1508.18,1505.07,1509.20,1505.01,9.373028e+07,62200
23,2024-11-28 11:20:00,600519.SH,1505.39,1503.55,1506.49,1503.55,7.721374e+07,51300
24,2024-11-28 11:25:00,600519.SH,1503.56,1504.29,1504.29,1502.00,6.568531e+07,43700
25,2024-11-28 11:30:00,600519.SH,1504.30,1503.21,1504.57,1503.03,1.323266e+07,8800
26,2024-11-28 13:01:00,600519.SH,1503.21,1505.33,1505.52,1503.21,6.468748e+07,43000
27,2024-11-28 13:05:00,600519.SH,1505.33,1508.41,1508.49,1505.00,5.965473e+07,39600
28,2024-11-28 13:10:00,600519.SH,1508.40,1506.00,1508.48,1506.00,2.471999e+07,16400
29,2024-11-28 13:15:00,600519.SH,1505.90,1508.15,1508.48,1505.21,3.617938e+07,24007
30,2024-11-28 13:20:00,600519.SH,1507.01,1507.01,1508.14,1506.64,2.592302e+07,17200
31,2024-11-28 13:25:00,600519.SH,1507.50,1511.20,1511.40,1507.48,4.135128e+07,27400
32,2024-11-28 13:30:00,600519.SH,1511.20,1511.70,1512.50,1510.46,3.506549e+07,23200
33,2024-11-28 13:35:00,600519.SH,1510.52,1512.42,1513.00,1510.52,4.278925e+07,28300
34,2024-11-28 13:40:00,600519.SH,1512.42,1512.58,1513.00,1511.55,4.628066e+07,30600
35,2024-11-28 13:45:00,600519.SH,1512.58,1514.75,1514.97,1512.58,4.540571e+07,30000
36,2024-11-28 13:50:00,600519.SH,1515.39,1518.01,1518.85,1514.50,1.149088e+08,75770
37,2024-11-28 13:55:00,600519.SH,1517.97,1515.00,1517.97,1515.00,3.503710e+07,23100
38,2024-11-28 14:00:00,600519.SH,1515.00,1514.45,1515.63,1513.20,4.119390e+07,27200
39,2024-11-28 14:05:00,600519.SH,1514.08,1514.77,1515.17,1513.10,3.907655e+07,25800
40,2024-11-28 14:10:00,600519.SH,1514.52,1517.50,1517.80,1514.52,5.321260e+07,35100
41,2024-11-28 14:15:00,600519.SH,1517.43,1518.00,1518.66,1517.43,5.040732e+07,33200
42,2024-11-28 14:20:00,600519.SH,1518.08,1516.72,1518.40,1516.31,7.587747e+07,50000
43,2024-11-28 14:25:00,600519.SH,1516.87,1516.76,1517.00,1516.30,3.109328e+07,20500
44,2024-11-28 14:30:00,600519.SH,1516.76,1515.89,1516.98,1514.00,5.440682e+07,35900
45,2024-11-28 14:35:00,600519.SH,1515.07,1515.25,1516.91,1515.01,5.505447e+07,36311
46,2024-11-28 14:40:00,600519.SH,1515.25,1515.00,1516.38,1514.50,6.334401e+07,41800
47,2024-11-28 14:45:00,600519.SH,1515.49,1514.56,1516.80,1514.00,8.697530e+07,57403
48,2024-11-28 14:50:00,600519.SH,1514.51,1513.93,1514.88,1511.02,9.002088e+07,59510
49,2024-11-28 14:55:00,600519.SH,1512.50,1514.90,1515.00,1512.00,6.716477e+07,44361
50,2024-11-28 15:00:00,600519.SH,1514.90,1518.00,1518.00,1514.90,1.507374e+08,99300

In [6]:
Kline(df_05m)

### 10 Minute

In [7]:
sql_10m = """
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount,
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
)
SELECT 
    date,
    instrument,
    DATE_TRUNC('hour', date) + INTERVAL '10 min' * CAST(FLOOR(EXTRACT(minute FROM date) / 10) AS BIGINT) AS _period,
    FIRST_VALUE(open) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS open,
    LAST_VALUE(close) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS close,
    MAX(high)         OVER (PARTITION BY _period, instrument) AS high,
    MIN(low)          OVER (PARTITION BY _period, instrument) AS low,
    SUM(amount)       OVER (PARTITION BY _period, instrument) AS amount,
    SUM(volume)       OVER (PARTITION BY _period, instrument) AS volume,
    row_number() OVER (PARTITION BY _period ORDER BY date) AS _rn,
FROM data_base
QUALIFY _rn = 1
ORDER BY date, instrument
"""

df_10m = get_dai_df(sql_10m, sd, ed, lag_min=240)
df_10m

,date,instrument,open,close,high,low,amount,volume
0,2024-11-28 09:25:00,600519.SH,1522.00,1522.00,1522.00,1522.00,4.748640e+07,31200
1,2024-11-28 09:31:00,600519.SH,1522.00,1519.10,1522.00,1510.01,4.541674e+08,299593
2,2024-11-28 09:40:00,600519.SH,1519.40,1522.16,1524.99,1519.40,2.759240e+08,181204
3,2024-11-28 09:50:00,600519.SH,1522.16,1519.29,1522.60,1519.20,1.690087e+08,111100
4,2024-11-28 10:00:00,600519.SH,1519.29,1517.35,1519.81,1516.98,1.345018e+08,88600
5,2024-11-28 10:10:00,600519.SH,1517.96,1514.13,1517.96,1513.00,1.570153e+08,103615
6,2024-11-28 10:20:00,600519.SH,1513.97,1514.12,1515.45,1513.00,1.082633e+08,71500
7,2024-11-28 10:30:00,600519.SH,1514.14,1513.80,1514.14,1512.95,1.138133e+08,75200
8,2024-11-28 10:40:00,600519.SH,1513.74,1513.27,1514.03,1512.06,1.180016e+08,78000
9,2024-11-28 10:50:00,600519.SH,1513.30,1513.35,1514.00,1512.32,1.016927e+08,67200
10,2024-11-28 11:00:00,600519.SH,1513.15,1508.78,1513.59,1508.00,2.030925e+08,134429
11,2024-11-28 11:10:00,600519.SH,1508.97,1505.07,1509.29,1505.01,1.579959e+08,104800
12,2024-11-28 11:20:00,600519.SH,1505.39,1504.29,1506.49,1502.00,1.428990e+08,95000
13,2024-11-28 11:30:00,600519.SH,1504.30,1503.21,1504.57,1503.03,1.323266e+07,8800
14,2024-11-28 13:01:00,600519.SH,1503.21,1508.41,1508.49,1503.21,1.243422e+08,82600
15,2024-11-28 13:10:00,600519.SH,1508.40,1508.15,1508.48,1505.21,6.089937e+07,40407
16,2024-11-28 13:20:00,600519.SH,1507.01,1511.20,1511.40,1506.64,6.727430e+07,44600
17,2024-11-28 13:30:00,600519.SH,1511.20,1512.42,1513.00,1510.46,7.785474e+07,51500
18,2024-11-28 13:40:00,600519.SH,1512.42,1514.75,1514.97,1511.55,9.168638e+07,60600
19,2024-11-28 13:50:00,600519.SH,1515.39,1515.00,1518.85,1514.50,1.499459e+08,98870
20,2024-11-28 14:00:00,600519.SH,1515.00,1514.77,1515.63,1513.10,8.027045e+07,53000
21,2024-11-28 14:10:00,600519.SH,1514.52,1518.00,1518.66,1514.52,1.036199e+08,68300
22,2024-11-28 14:20:00,600519.SH,1518.08,1516.76,1518.40,1516.30,1.069707e+08,70500
23,2024-11-28 14:30:00,600519.SH,1516.76,1515.25,1516.98,1514.00,1.094613e+08,72211
24,2024-11-28 14:40:00,600519.SH,1515.25,1514.56,1516.80,1514.00,1.503193e+08,99203
25,2024-11-28 14:50:00,600519.SH,1514.51,1514.90,1515.00,1511.02,1.571856e+08,103871
26,2024-11-28 15:00:00,600519.SH,1514.90,1518.00,1518.00,1514.90,1.507374e+08,99300

In [8]:
Kline(df_10m)

### 15 Minute

In [9]:
sql_15m = """
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount,
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
)
SELECT 
    date,
    instrument,
    DATE_TRUNC('hour', date) + INTERVAL '15 min' * CAST(FLOOR(EXTRACT(minute FROM date) / 15) AS BIGINT) AS _period,
    FIRST_VALUE(open) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS open,
    LAST_VALUE(close) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS close,
    MAX(high)         OVER (PARTITION BY _period, instrument) AS high,
    MIN(low)          OVER (PARTITION BY _period, instrument) AS low,
    SUM(amount)       OVER (PARTITION BY _period, instrument) AS amount,
    SUM(volume)       OVER (PARTITION BY _period, instrument) AS volume,
    row_number() OVER (PARTITION BY _period ORDER BY date) AS _rn,
FROM data_base
QUALIFY _rn = 1
ORDER BY date, instrument
"""

df_15m = get_dai_df(sql_15m, sd, ed, lag_min=240)
df_15m

,date,instrument,open,close,high,low,amount,volume
0,2024-11-28 09:25:00,600519.SH,1522.00,1522.00,1522.00,1522.00,4.748640e+07,31200
1,2024-11-28 09:31:00,600519.SH,1522.00,1524.16,1524.99,1510.01,6.257600e+08,412293
2,2024-11-28 09:45:00,600519.SH,1524.80,1519.29,1524.91,1519.20,2.733401e+08,179604
3,2024-11-28 10:00:00,600519.SH,1519.29,1515.01,1519.81,1515.00,2.083788e+08,137318
4,2024-11-28 10:15:00,600519.SH,1515.00,1514.12,1515.52,1513.00,1.914016e+08,126397
5,2024-11-28 10:30:00,600519.SH,1514.14,1512.20,1514.14,1512.06,1.756803e+08,116100
6,2024-11-28 10:45:00,600519.SH,1512.18,1513.35,1514.03,1512.10,1.578273e+08,104300
7,2024-11-28 11:00:00,600519.SH,1513.15,1508.10,1513.59,1508.00,2.673581e+08,177029
8,2024-11-28 11:15:00,600519.SH,1508.18,1504.29,1509.20,1502.00,2.366293e+08,157200
9,2024-11-28 11:30:00,600519.SH,1504.30,1503.21,1504.57,1503.03,1.323266e+07,8800
10,2024-11-28 13:01:00,600519.SH,1503.21,1506.00,1508.49,1503.21,1.490622e+08,99000
11,2024-11-28 13:15:00,600519.SH,1505.90,1511.20,1511.40,1505.21,1.034537e+08,68607
12,2024-11-28 13:30:00,600519.SH,1511.20,1512.58,1513.00,1510.46,1.241354e+08,82100
13,2024-11-28 13:45:00,600519.SH,1512.58,1515.00,1518.85,1512.58,1.953517e+08,128870
14,2024-11-28 14:00:00,600519.SH,1515.00,1517.50,1517.80,1513.10,1.334831e+08,88100
15,2024-11-28 14:15:00,600519.SH,1517.43,1516.76,1518.66,1516.30,1.573781e+08,103700
16,2024-11-28 14:30:00,600519.SH,1516.76,1515.00,1516.98,1514.00,1.728053e+08,114011
17,2024-11-28 14:45:00,600519.SH,1515.49,1514.90,1516.80,1511.02,2.441609e+08,161274
18,2024-11-28 15:00:00,600519.SH,1514.90,1518.00,1518.00,1514.90,1.507374e+08,99300

In [10]:
Kline(df_15m)

### 20 Minute

In [11]:
sql_20m = """
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount,
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
),
data_periods AS (
    SELECT
        *,
        CASE 
            WHEN EXTRACT(minute FROM date) BETWEEN 11 AND 30 THEN DATE_TRUNC('hour', date) + INTERVAL '11 minute'
            WHEN EXTRACT(minute FROM date) BETWEEN 31 AND 50 THEN DATE_TRUNC('hour', date) + INTERVAL '31 minute'
            ELSE DATE_TRUNC('hour', date) + INTERVAL '51 minute'
        END AS period
    FROM data_base
)
SELECT 
    date,
    instrument,
    period AS _period,
    FIRST_VALUE(open) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS open,
    LAST_VALUE(close) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS close,
    MAX(high)         OVER (PARTITION BY _period, instrument) AS high,
    MIN(low)          OVER (PARTITION BY _period, instrument) AS low,
    SUM(amount)       OVER (PARTITION BY _period, instrument) AS amount,
    SUM(volume)       OVER (PARTITION BY _period, instrument) AS volume,
    row_number() OVER (PARTITION BY _period ORDER BY date) AS _rn,
FROM data_periods
QUALIFY _rn = 1
ORDER BY date, instrument
"""

df_20m = get_dai_df(sql_20m, sd, ed, lag_min=240)
df_20m

,date,instrument,open,close,high,low,amount,volume
0,2024-11-28 09:25:00,600519.SH,1522.00,1522.00,1522.00,1522.00,4.748640e+07,31200
1,2024-11-28 09:31:00,600519.SH,1522.00,1521.93,1524.99,1510.01,7.478995e+08,492497
2,2024-11-28 09:51:00,600519.SH,1521.93,1519.29,1522.60,1519.20,1.512007e+08,99400
3,2024-11-28 10:00:00,600519.SH,1519.29,1513.35,1519.81,1512.32,2.354598e+08,155300
4,2024-11-28 10:11:00,600519.SH,1517.51,1513.30,1517.90,1513.00,2.708594e+08,178815
5,2024-11-28 10:31:00,600519.SH,1513.31,1513.09,1514.14,1512.06,2.269688e+08,150000
6,2024-11-28 11:00:00,600519.SH,1513.15,1509.00,1513.59,1508.00,2.169742e+08,143629
7,2024-11-28 11:11:00,600519.SH,1509.04,1503.21,1509.29,1502.00,3.002459e+08,199400
8,2024-11-28 13:01:00,600519.SH,1503.21,1515.00,1518.85,1503.21,2.496815e+08,165256
9,2024-11-28 13:11:00,600519.SH,1508.00,1511.18,1511.40,1505.21,1.265216e+08,83907
10,2024-11-28 13:31:00,600519.SH,1511.18,1516.86,1516.87,1510.46,1.957999e+08,129414
11,2024-11-28 14:00:00,600519.SH,1515.00,1514.90,1515.63,1511.02,2.288326e+08,151171
12,2024-11-28 14:11:00,600519.SH,1514.88,1516.61,1518.66,1514.70,2.084773e+08,137400
13,2024-11-28 14:31:00,600519.SH,1516.79,1513.00,1516.91,1513.00,2.705174e+08,178514
14,2024-11-28 15:00:00,600519.SH,1514.90,1518.00,1518.00,1514.90,1.507374e+08,99300

In [12]:
Kline(df_20m)

### 30 Minute

In [13]:
sql_30m = """
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount,
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
)
SELECT 
    date,
    instrument,
    DATE_TRUNC('hour', date) + INTERVAL '30 min' * CAST(FLOOR(EXTRACT(minute FROM date) / 30) AS BIGINT) AS _period,
    FIRST_VALUE(open) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS open,
    LAST_VALUE(close) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS close,
    MAX(high)         OVER (PARTITION BY _period, instrument) AS high,
    MIN(low)          OVER (PARTITION BY _period, instrument) AS low,
    SUM(amount)       OVER (PARTITION BY _period, instrument) AS amount,
    SUM(volume)       OVER (PARTITION BY _period, instrument) AS volume,
    row_number() OVER (PARTITION BY _period ORDER BY date) AS _rn,
FROM data_base
QUALIFY _rn = 1
ORDER BY date, instrument
"""

df_30m = get_dai_df(sql_30m, sd, ed, lag_min=240)
df_30m

,date,instrument,open,close,high,low,amount,volume
0,2024-11-28 09:25:00,600519.SH,1522.00,1522.00,1522.00,1522.00,4.748640e+07,31200
1,2024-11-28 09:31:00,600519.SH,1522.00,1519.29,1524.99,1510.01,8.991002e+08,591897
2,2024-11-28 10:00:00,600519.SH,1519.29,1514.12,1519.81,1513.00,3.997804e+08,263715
3,2024-11-28 10:30:00,600519.SH,1514.14,1513.35,1514.14,1512.06,3.335076e+08,220400
4,2024-11-28 11:00:00,600519.SH,1513.15,1504.29,1513.59,1502.00,5.039874e+08,334229
5,2024-11-28 11:30:00,600519.SH,1504.30,1503.21,1504.57,1503.03,1.323266e+07,8800
6,2024-11-28 13:01:00,600519.SH,1503.21,1511.20,1511.40,1503.21,2.525159e+08,167607
7,2024-11-28 13:30:00,600519.SH,1511.20,1515.00,1518.85,1510.46,3.194871e+08,210970
8,2024-11-28 14:00:00,600519.SH,1515.00,1516.76,1518.66,1513.10,2.908611e+08,191800
9,2024-11-28 14:30:00,600519.SH,1516.76,1514.90,1516.98,1511.02,4.169662e+08,275285
10,2024-11-28 15:00:00,600519.SH,1514.90,1518.00,1518.00,1514.90,1.507374e+08,99300

In [14]:
Kline(df_30m)

### 1 Hour

In [15]:
sql_1h = """
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
),
data_periods AS (
    SELECT
        *,
        CASE 
            WHEN date::time >= TIME '09:25:00' AND date::time <= TIME '10:30:00' THEN DATE_TRUNC('day', date) + INTERVAL '09:25:00'
            WHEN date::time >= TIME '10:30:00' AND date::time <= TIME '11:30:00' THEN DATE_TRUNC('day', date) + INTERVAL '10:30:00'
            WHEN date::time >= TIME '13:01:00' AND date::time <= TIME '14:00:00' THEN DATE_TRUNC('day', date) + INTERVAL '13:01:00'
            WHEN date::time >= TIME '14:00:00' AND date::time <= TIME '15:00:00' THEN DATE_TRUNC('day', date) + INTERVAL '14:00:00'
        END AS period
    FROM data_base
    WHERE date::time >= TIME '09:25:00' AND date::time <= TIME '15:00:00'
)
SELECT 
    date,
    instrument,
    period AS _period,
    FIRST_VALUE(open) OVER (PARTITION BY _period, instrument ORDER BY date) AS open,
    LAST_VALUE(close) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS close,
    MAX(high)         OVER (PARTITION BY _period, instrument) AS high,
    MIN(low)          OVER (PARTITION BY _period, instrument) AS low,
    SUM(amount)       OVER (PARTITION BY _period, instrument) AS amount,
    SUM(volume)       OVER (PARTITION BY _period, instrument) AS volume,
    ROW_NUMBER()      OVER (PARTITION BY _period ORDER BY date) AS _rn
FROM data_periods
QUALIFY _rn = 1
ORDER BY _period, instrument
"""

df_1h = get_dai_df(sql_1h, sd, ed, lag_min=240)
df_1h

,date,instrument,open,close,high,low,amount,volume
0,2024-11-28 09:25:00,600519.SH,1522.00,1513.30,1524.99,1510.01,1.359537e+09,895512
1,2024-11-28 10:31:00,600519.SH,1513.31,1503.21,1514.14,1502.00,8.375581e+08,554729
2,2024-11-28 13:01:00,600519.SH,1503.21,1515.01,1518.85,1503.21,5.804874e+08,384177
3,2024-11-28 14:01:00,600519.SH,1515.55,1518.00,1518.66,1511.02,8.500803e+08,560785

In [16]:
Kline(df_1h)

### 2 Hour

In [17]:
sql_2h = """
WITH 
data_base AS (
    SELECT
        date,
        instrument,
        open,
        close,
        high,
        low,
        volume,
        amount
    FROM cn_stock_bar1m
    WHERE instrument = '600519.SH'
),
data_periods AS (
    SELECT
        *,
        CASE 
            WHEN date::time >= TIME '09:25:00' AND date::time <= TIME '11:30:00' THEN DATE_TRUNC('day', date) + INTERVAL '09:25:00'
            WHEN date::time >= TIME '13:01:00' AND date::time <= TIME '15:00:00' THEN DATE_TRUNC('day', date) + INTERVAL '13:01:00'
        END AS period
    FROM data_base
    WHERE date::time >= TIME '09:25:00' AND date::time <= TIME '15:00:00'
)
SELECT 
    date,
    instrument,
    period AS _period,
    FIRST_VALUE(open) OVER (PARTITION BY _period, instrument ORDER BY date) AS open,
    LAST_VALUE(close) OVER (PARTITION BY _period, instrument ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS close,
    MAX(high)         OVER (PARTITION BY _period, instrument) AS high,
    MIN(low)          OVER (PARTITION BY _period, instrument) AS low,
    SUM(amount)       OVER (PARTITION BY _period, instrument) AS amount,
    SUM(volume)       OVER (PARTITION BY _period, instrument) AS volume,
    ROW_NUMBER()      OVER (PARTITION BY _period ORDER BY date) AS _rn
FROM data_periods
QUALIFY _rn = 1
ORDER BY _period, instrument
"""

df_2h = get_dai_df(sql_2h, sd, ed, lag_min=240)
df_2h

,date,instrument,open,close,high,low,amount,volume
0,2024-11-28 09:25:00,600519.SH,1522.00,1503.21,1524.99,1502.00,2.197095e+09,1450241
1,2024-11-28 13:01:00,600519.SH,1503.21,1518.00,1518.85,1503.21,1.430568e+09,944962

In [18]:
Kline(df_2h)