In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Resources_Collection/BigQuant_Resources_Collection/00_General_Resources/General_Tool")
sys.path.append("/home/aiuser/work/userlib/BigQuant_Resources_Collection/BigQuant_Resources_Collection/00_General_Resources/General_Factor")
from cn_general_tool import *
from cn_general_factors_vpta import *

In [2]:
sd, ed = get_sd_ed('2024-11-25', '2024-11-25')

In [3]:
alpha_vpta_mavg(sd, ed, col="close", n=5, data_base="cn_stock_index_bar1d")

         date  instrument  alpha_vpta_mavg_close_5
0  2024-11-25   399006.SZ               2228.21662
1  2024-11-25   399001.SZ              10650.03040
2  2024-11-25   000001.SH               3323.07086
3  2024-11-25   899050.BJ               1321.07140
4  2024-11-25   000300.SH               3933.15032
5  2024-11-25   000510.SH               4647.35600
6  2024-11-25   399330.SZ               4740.89496
7  2024-11-25  000985.CSI               4833.87646
8  2024-11-25   000903.SH               3715.68804
9  2024-11-25   000852.SH               6145.17380
10 2024-11-25   000688.SH                987.85814
11 2024-11-25   000016.SH               2642.36088
12 2024-11-25   000905.SH               5880.03994